# Generated by Django 3.1.7 on 2021-03-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketball_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game_date',
            field=models.DateTimeField(),
        ),
    ]
