# Generated by Django 3.1.7 on 2021-03-24 03:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basketball_api', '0002_auto_20210323_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
