# Generated by Django 3.1.7 on 2021-03-24 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketball_api', '0003_auto_20210324_0835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
